package conversation

import (
	"github.com/gin-gonic/gin"

	"github.com/DEEIX-AI/DEEIX-Chat/backend/internal/transport/http/middleware"
)

// RegisterRoutes 注册会话域路由。
func (m *Module) RegisterRoutes(authRequired *gin.RouterGroup, gate middleware.FeatureGate) {
	authRequired.POST("/conversations", m.Handler.CreateConversation)
	authRequired.GET("/conversations", m.Handler.ListConversations)
	authRequired.GET("/conversations/search", m.Handler.SearchConversations)
	authRequired.GET("/conversations/default-model-candidate", m.Handler.GetConversationDefaultModelCandidate)
	authRequired.GET("/conversation-projects", m.Handler.ListConversationProjects)
	authRequired.POST("/conversation-projects", m.Handler.CreateConversationProject)
	authRequired.GET("/conversation-projects/:id/workspace", m.Handler.GetProjectWorkspace)
	authRequired.GET("/conversation-projects/:id/files", m.Handler.ListProjectFiles)
	authRequired.PUT("/conversation-projects/:id/files", m.Handler.WriteProjectFile)
	authRequired.POST("/conversation-projects/:id/files/import", m.Handler.ImportProjectZIP)
	authRequired.GET("/conversation-projects/:id/files/:file_id/content", m.Handler.GetProjectFileContent)
	authRequired.DELETE("/conversation-projects/:id/files/:file_id", m.Handler.DeleteProjectFile)
	authRequired.GET("/conversation-projects/:id/archive", m.Handler.DownloadProjectArchive)
	authRequired.POST("/conversation-projects/reorder", m.Handler.ReorderConversationProjects)
	authRequired.DELETE("/conversation-projects/:id", m.Handler.DeleteConversationProject)
	authRequired.POST("/conversations/project", m.Handler.BatchSetConversationProject)
	authRequired.GET("/conversation-roles", m.Handler.ListConversationRoles)
	authRequired.POST("/conversation-roles", m.Handler.CreateConversationRole)
	authRequired.POST("/conversation-roles/reorder", m.Handler.ReorderConversationRoles)
	authRequired.GET("/conversation-roles/:id", m.Handler.GetConversationRole)
	authRequired.PATCH("/conversation-roles/:id", m.Handler.UpdateConversationRole)
	authRequired.DELETE("/conversation-roles/:id", m.Handler.DeleteConversationRole)
	authRequired.GET("/conversations/export", m.Handler.ExportAllConversations)
	authRequired.GET("/conversations/:id", m.Handler.GetConversation)
	authRequired.POST("/conversations/:id/read", m.Handler.MarkConversationRead)
	authRequired.GET("/conversations/:id/export", m.Handler.ExportConversation)
	authRequired.PATCH("/conversations/:id/title", m.Handler.RenameConversation)
	authRequired.POST("/conversations/:id/title/regenerate", m.Handler.RegenerateConversationTitle)
	authRequired.PATCH("/conversations/:id/labels", m.Handler.UpdateConversationLabels)
	authRequired.PATCH("/conversations/:id/star", m.Handler.SetConversationStar)
	authRequired.PATCH("/conversations/:id/archive", m.Handler.SetConversationArchive)
	authRequired.PATCH("/conversations/:id/project", m.Handler.SetConversationProject)
	authRequired.DELETE("/conversations/:id", m.Handler.DeleteConversation)
	sharing := authRequired.Group("", gate.Require("sharing"))
	sharing.POST("/conversations/shares/revoke", m.Handler.RevokeConversationShares)
	sharing.GET("/conversations/:id/share", m.Handler.GetConversationShare)
	sharing.POST("/conversations/:id/share", m.Handler.CreateConversationShare)
	sharing.DELETE("/conversations/:id/share", m.Handler.RevokeConversationShare)
	sharing.POST("/conversations/:id/share/regenerate", m.Handler.RegenerateConversationShare)
	sharing.POST("/shared-conversations/:share_id/clone", m.Handler.CloneSharedConversation)
	authRequired.GET("/conversations/:id/messages", m.Handler.ListMessages)
	authRequired.GET("/conversations/:id/messages/preview", m.Handler.ListConversationPreviewMessages)
	authRequired.GET("/conversations/:id/runs", m.Handler.ListConversationRuns)
	authRequired.POST("/conversations/:id/messages", m.Handler.SendMessage)
	authRequired.POST("/conversations/:id/messages/stream", m.Handler.StreamMessage)
	authRequired.POST("/temporary-chat/messages/stream", m.Handler.StreamTemporaryChatMessage)
	authRequired.POST("/conversations/:id/messages/:message_id/fork", m.Handler.ForkConversationFromMessage)
	authRequired.DELETE("/conversations/:id/messages/:message_id", m.Handler.DeleteMessage)
	authRequired.POST("/conversations/:id/media/images/generations/stream", m.Handler.StreamImageGeneration)
	authRequired.POST("/conversations/:id/media/images/edits/stream", m.Handler.StreamImageEdit)
	authRequired.POST("/conversations/:id/media/videos/generations/stream", m.Handler.StreamVideoGeneration)
	authRequired.POST("/conversations/:id/media/videos/extensions/stream", m.Handler.StreamVideoExtension)
	authRequired.GET("/context-artifacts/:id", m.Handler.GetContextArtifact)
	authRequired.POST("/conversation-runs/statuses", m.Handler.GetConversationRunStatuses)
	authRequired.GET("/conversation-runs/stream", m.Handler.StreamActiveMessageGenerations)
	authRequired.GET("/conversation-runs/:run_id/stream", m.Handler.ResumeMessageGenerationStream)
	authRequired.GET("/conversation-runs/:run_id/tool-calls/:tool_call_id", m.Handler.GetConversationToolCallDetail)
	authRequired.POST("/conversation-runs/:run_id/cancel", m.Handler.CancelMessageGeneration)
	authRequired.POST("/conversation-runs/:run_id/media/requery", m.Handler.RequeryMediaVideoRun)
	authRequired.POST("/conversation-runs/:run_id/media/artifact-retry", m.Handler.RetryMediaImageArtifact)
	authRequired.PATCH("/messages/:id", m.Handler.UpdateMessage)
	authRequired.PUT("/messages/:id/feedback", m.Handler.SetMessageFeedback)
	authRequired.POST("/files", m.Handler.UploadFile)
	authRequired.GET("/files", m.Handler.ListFiles)
	authRequired.POST("/files/processing/statuses", m.Handler.GetFileProcessingStatuses)
	authRequired.POST("/files/embeddings", m.Handler.SubmitFileEmbeddings)
	authRequired.GET("/files/:file_id/processing", m.Handler.GetFileProcessingStatus)
	authRequired.GET("/files/:file_id/extract", m.Handler.GetFileExtract)
	authRequired.PATCH("/files/:file_id", m.Handler.UpdateFile)
	authRequired.GET("/files/:file_id/content", m.Handler.GetFileContent)
	authRequired.POST("/files/:file_id/share", m.Handler.CreateFileShare)
	authRequired.GET("/files/:file_id/share", m.Handler.GetFileShare)
	authRequired.DELETE("/files/:file_id/share", m.Handler.RevokeFileShare)
	authRequired.GET("/files/:file_id/thumbnail", m.Handler.GetFileThumbnail)
	authRequired.DELETE("/files/:file_id", m.Handler.DeleteFile)
	authRequired.GET("/runtime/chat-file-policy", m.Handler.GetChatFilePolicy)
}

// RegisterPublicRoutes 注册不需要登录的会话公开路由。
func (m *Module) RegisterPublicRoutes(public *gin.RouterGroup, gate middleware.FeatureGate) {
	sharing := public.Group("", gate.Require("sharing"))
	sharing.GET("/shared-conversations/:share_id", m.Handler.GetPublicSharedConversation)
	sharing.GET("/shared-conversations/:share_id/files/:file_id/content", m.Handler.GetPublicSharedFileContent)
	sharing.GET("/shared-files/:share_id", m.Handler.GetPublicFileShare)
	sharing.GET("/shared-files/:share_id/content", m.Handler.GetPublicFileShareContent)
	public.GET("/files/:file_id/signed-content", m.Handler.GetSignedFileContent)
	public.GET("/files/:file_id/signed-thumbnail", m.Handler.GetSignedFileThumbnail)
}
